// Kits: four voices + sound tweaks per lane. Applying a kit changes sounds, never patterns.
export const KITS = {
  common: { name: 'Common', lanes: [{ voice: 'kick' }, { voice: 'snare' }, { voice: 'hat', sound: { decay: 0.3 } }, { voice: 'wood', sound: { decay: 0.3, color: 0.6 } }] },
  boombox: { name: '808‑ish', lanes: [{ voice: 'sub', sound: { decay: 0.7, color: 0.3 } }, { voice: 'clap', sound: { snap: 0.6 } }, { voice: 'hat', sound: { decay: 0.2, color: 0.3, tone: 0.9 } }, { voice: 'cowbell', sound: { decay: 0.35 } }] },
  industrial: { name: 'Industrial', lanes: [{ voice: 'kick', sound: { drive: 0.6, snap: 0.9, color: 0.8 } }, { voice: 'glitch', sound: { color: 0.3, snap: 0.5 } }, { voice: 'zap', sound: { decay: 0.4, snap: 0.7 } }, { voice: 'gong', sound: { decay: 0.4, drive: 0.3 } }] },
  skins: { name: 'Wood & skin', lanes: [{ voice: 'tom', sound: { decay: 0.5, color: 0.5 } }, { voice: 'rim', sound: { snap: 0.7 } }, { voice: 'shaker', sound: { decay: 0.35, tone: 0.9 } }, { voice: 'wood', sound: { decay: 0.4, color: 0.4 } }] },
  space: { name: 'Space', lanes: [{ voice: 'sub', sound: { decay: 0.9, send: 0.4 } }, { voice: 'bell', sound: { decay: 0.6, send: 0.5 } }, { voice: 'blip', sound: { decay: 0.3, send: 0.6, pan: 0.7 } }, { voice: 'gong', sound: { decay: 0.8, send: 0.6, pan: 0.3 } }] },
  glitch: { name: 'Glitch', lanes: [{ voice: 'snap', sound: { decay: 0.4, drive: 0.4 } }, { voice: 'zap', sound: { decay: 0.3, color: 0.2 } }, { voice: 'glitch', sound: { color: 0.6 } }, { voice: 'blip', sound: { decay: 0.2, snap: 0.9 } }] },
  house909: { name: '909 house', lanes: [{ voice: 'kick909', sound: { decay: 0.45 } }, { voice: 'clap', sound: { snap: 0.5, send: 0.2 } }, { voice: 'ophat', sound: { decay: 0.35 } }, { voice: 'ride', sound: { decay: 0.4, level: 0.6 } }] },
  techno: { name: 'Techno', lanes: [{ voice: 'kick909', sound: { decay: 0.55, drive: 0.35, color: 0.6 } }, { voice: 'rim', sound: { snap: 0.8, send: 0.3 } }, { voice: 'hat', sound: { decay: 0.15, tone: 0.95 } }, { voice: 'noiseburst', sound: { decay: 0.3, send: 0.4 } }] },
  trap: { name: 'Trap', lanes: [{ voice: 'kick808', sound: { decay: 0.75, snap: 0.5 } }, { voice: 'snare808', sound: { decay: 0.35, snap: 0.7 } }, { voice: 'hat', sound: { decay: 0.12, tone: 0.95 } }, { voice: 'snap2', sound: { decay: 0.3, send: 0.3 } }] },
  gabber: { name: 'Gabber', lanes: [{ voice: 'hardkick', sound: { decay: 0.55, color: 0.9 } }, { voice: 'clap', sound: { drive: 0.5, snap: 0.8 } }, { voice: 'ophat', sound: { decay: 0.25, drive: 0.3 } }, { voice: 'crash', sound: { decay: 0.5, level: 0.5 } }] },
  electro: { name: 'Electro', lanes: [{ voice: 'kick808', sound: { decay: 0.45, snap: 0.8 } }, { voice: 'snare808', sound: { decay: 0.3 } }, { voice: 'laser', sound: { decay: 0.3, send: 0.3 } }, { voice: 'click', sound: { color: 0.5 } }] },
  breaks: { name: 'Breakbeat', lanes: [{ voice: 'kick', sound: { decay: 0.35, drive: 0.2 } }, { voice: 'snare', sound: { decay: 0.35, snap: 0.6, drive: 0.25 } }, { voice: 'ride', sound: { decay: 0.35 } }, { voice: 'tamb', sound: { decay: 0.3 } }] },
  latin: { name: 'Latin', lanes: [{ voice: 'conga', sound: { decay: 0.45, snap: 0.5 } }, { voice: 'bongo', sound: { decay: 0.3, color: 0.4 } }, { voice: 'clave', sound: { decay: 0.2 } }, { voice: 'cowbell', sound: { decay: 0.3, tone: 0.8 } }] },
  afro: { name: 'Afro', lanes: [{ voice: 'conga', sound: { decay: 0.55, snap: 0.2 } }, { voice: 'shaker', sound: { decay: 0.3 } }, { voice: 'tabla', sound: { decay: 0.45, color: 0.4 } }, { voice: 'cuica', sound: { decay: 0.35, send: 0.2 } }] },
  jazz: { name: 'Brushes', lanes: [{ voice: 'softkick', sound: { decay: 0.4 } }, { voice: 'brush', sound: { decay: 0.5, color: 0.4 } }, { voice: 'ride', sound: { decay: 0.6, level: 0.6 } }, { voice: 'rim', sound: { decay: 0.3, snap: 0.3 } }] },
  lofi: { name: 'Lo-fi', lanes: [{ voice: 'softkick', sound: { decay: 0.45, tone: 0.5 } }, { voice: 'snare', sound: { decay: 0.3, tone: 0.55, drive: 0.15 } }, { voice: 'shaker', sound: { decay: 0.25, tone: 0.6 } }, { voice: 'vinyl', sound: { decay: 0.3, snap: 0.6, level: 0.5 } }] },
  mallets: { name: 'Mallets', lanes: [{ voice: 'marimba', sound: { decay: 0.45, send: 0.3 } }, { voice: 'steel', sound: { decay: 0.5, send: 0.3 } }, { voice: 'kalimba', sound: { decay: 0.5, send: 0.4 } }, { voice: 'bell', sound: { decay: 0.4, send: 0.5 } }] },
  minimal: { name: 'Minimal', lanes: [{ voice: 'kick909', sound: { decay: 0.3, color: 0.3 } }, { voice: 'click', sound: { color: 0.3 } }, { voice: 'clave', sound: { decay: 0.15, send: 0.3 } }, { voice: 'blip', sound: { decay: 0.15, send: 0.5 } }] },
};
export const KIT_KEYS = Object.keys(KITS);
