// Voice library for Orbits. Each voice: make(T, out) → nodes (connected to `out`), hit(T, nodes, p, time) where
// p = { vel, tune (-1..1), dec (seconds), snap, color (0..1) } already derived from the lane's sound params.
const mf = (T, midi) => T.Frequency(midi, 'midi').toFrequency();
const V = {};
V.kick = { label: 'kick', make: (T, out) => ({ body: new T.MembraneSynth({ pitchDecay: 0.04, octaves: 7, envelope: { attack: 0.001, decay: 0.35, sustain: 0 }, volume: -2 }).connect(out), click: new T.NoiseSynth({ envelope: { attack: 0.001, decay: 0.02, sustain: 0 }, volume: -18 }).connect(out) }),
  hit: (T, n, p, t) => { n.body.set({ pitchDecay: 0.01 + p.color * 0.12, envelope: { decay: p.dec } }); n.body.triggerAttackRelease(mf(T, 36 + p.tune * 12), p.dec, t, p.vel); if (p.snap > 0.05) n.click.triggerAttackRelease(0.02, t, p.vel * p.snap); } };
V.sub = { label: 'sub', make: (T, out) => ({ o: new T.Synth({ oscillator: { type: 'sine' }, envelope: { attack: 0.005, decay: 0.6, sustain: 0.2, release: 0.3 }, volume: 0 }).connect(out) }),
  hit: (T, n, p, t) => { n.o.set({ envelope: { decay: p.dec * 1.5, sustain: p.color * 0.4 } }); n.o.triggerAttackRelease(mf(T, 29 + p.tune * 12), p.dec * 1.5, t, p.vel); } };
V.snare = { label: 'snare', make: (T, out) => ({ noise: new T.NoiseSynth({ envelope: { attack: 0.001, decay: 0.18, sustain: 0 }, volume: -8 }).connect(out), body: new T.Synth({ oscillator: { type: 'triangle' }, envelope: { attack: 0.001, decay: 0.12, sustain: 0 }, volume: -12 }).connect(out) }),
  hit: (T, n, p, t) => { n.noise.set({ envelope: { decay: p.dec * 0.6 } }); n.body.set({ envelope: { decay: p.dec * 0.35 } }); n.noise.triggerAttackRelease(p.dec * 0.6, t, p.vel * (0.3 + p.color * 0.7)); n.body.triggerAttackRelease(mf(T, 57 + p.tune * 12), p.dec * 0.35, t, p.vel * (0.4 + (1 - p.color) * 0.6) * (0.5 + p.snap * 0.5)); } };
V.clap = { label: 'clap', make: (T, out) => ({ n: new T.NoiseSynth({ noise: { type: 'pink' }, envelope: { attack: 0.001, decay: 0.09, sustain: 0 }, volume: -6 }).connect(out) }),
  hit: (T, n, p, t) => { const bursts = 2 + Math.round(p.snap * 3); for (let i = 0; i < bursts; i++) n.n.triggerAttackRelease(i === bursts - 1 ? p.dec * 0.8 : 0.02, t + i * 0.011, p.vel * (i === bursts - 1 ? 1 : 0.6)); } };
V.rim = { label: 'rim', make: (T, out) => ({ o: new T.Synth({ oscillator: { type: 'square' }, envelope: { attack: 0.001, decay: 0.05, sustain: 0 }, volume: -10 }).connect(out), c: new T.NoiseSynth({ envelope: { attack: 0.001, decay: 0.03, sustain: 0 }, volume: -14 }).connect(out) }),
  hit: (T, n, p, t) => { n.o.triggerAttackRelease(mf(T, 81 + p.tune * 12 + p.color * 7), Math.min(0.12, p.dec * 0.2), t, p.vel); n.c.triggerAttackRelease(0.03, t, p.vel * p.snap); } };
V.tom = { label: 'tom', make: (T, out) => ({ m: new T.MembraneSynth({ pitchDecay: 0.08, octaves: 3, envelope: { attack: 0.001, decay: 0.4, sustain: 0 }, volume: -4 }).connect(out) }),
  hit: (T, n, p, t) => { n.m.set({ pitchDecay: 0.03 + p.snap * 0.15, octaves: 1 + p.color * 4, envelope: { decay: p.dec } }); n.m.triggerAttackRelease(mf(T, 55 + p.tune * 24), p.dec, t, p.vel); } };
V.hat = { label: 'hat', make: (T, out) => ({ m: new T.MetalSynth({ envelope: { attack: 0.001, decay: 0.08, release: 0.02 }, harmonicity: 5.1, modulationIndex: 32, resonance: 4000, octaves: 1.5, volume: -16 }).connect(out), n: new T.NoiseSynth({ envelope: { attack: 0.001, decay: 0.05, sustain: 0 }, volume: -22 }).connect(out) }),
  hit: (T, n, p, t) => { n.m.set({ envelope: { decay: p.dec * 0.5 }, harmonicity: 3 + p.color * 6, modulationIndex: 10 + p.snap * 50 }); n.m.triggerAttackRelease(mf(T, 84 + p.tune * 12), p.dec * 0.5, t, p.vel * 0.8); if (p.color > 0.6) n.n.triggerAttackRelease(p.dec * 0.3, t, p.vel * (p.color - 0.6)); } };
V.shaker = { label: 'shaker', make: (T, out) => ({ n: new T.NoiseSynth({ noise: { type: 'pink' }, envelope: { attack: 0.01, decay: 0.07, sustain: 0 }, volume: -14 }).connect(out) }),
  hit: (T, n, p, t) => { n.n.set({ envelope: { attack: 0.003 + (1 - p.snap) * 0.03, decay: 0.03 + p.dec * 0.15 } }); n.n.triggerAttackRelease(0.03 + p.dec * 0.15, t, p.vel); } };
V.cowbell = { label: 'cowbell', make: (T, out) => ({ a: new T.Synth({ oscillator: { type: 'square' }, envelope: { attack: 0.001, decay: 0.3, sustain: 0 }, volume: -16 }).connect(out), b: new T.Synth({ oscillator: { type: 'square' }, envelope: { attack: 0.001, decay: 0.3, sustain: 0 }, volume: -16 }).connect(out) }),
  hit: (T, n, p, t) => { const f = 560 * Math.pow(2, p.tune); n.a.set({ envelope: { decay: p.dec * 0.5 } }); n.b.set({ envelope: { decay: p.dec * 0.5 } }); n.a.triggerAttackRelease(f, p.dec * 0.5, t, p.vel); n.b.triggerAttackRelease(f * (1.45 + p.color * 0.2), p.dec * 0.5, t, p.vel * 0.8); } };
V.wood = { label: 'wood', make: (T, out) => ({ p: new T.PluckSynth({ attackNoise: 2, dampening: 3000, resonance: 0.7, volume: -4 }).connect(out) }),
  hit: (T, n, p, t) => { n.p.set({ dampening: 800 + p.color * 6000, resonance: 0.4 + p.dec * 0.55, attackNoise: 0.5 + p.snap * 4 }); n.p.triggerAttackRelease(mf(T, 60 + p.tune * 24), p.dec, t, p.vel); } };
V.blip = { label: 'blip', make: (T, out) => ({ o: new T.Synth({ oscillator: { type: 'sine' }, envelope: { attack: 0.001, decay: 0.08, sustain: 0 }, volume: -8 }).connect(out) }),
  hit: (T, n, p, t) => { n.o.set({ oscillator: { type: p.color > 0.5 ? 'triangle' : 'sine' }, envelope: { decay: Math.min(0.3, p.dec * 0.3) } }); n.o.triggerAttackRelease(mf(T, 84 + p.tune * 24 + Math.round(p.snap * 12)), Math.min(0.3, p.dec * 0.3), t, p.vel); } };
V.bell = { label: 'bell', make: (T, out) => ({ f: new T.FMSynth({ harmonicity: 3.5, modulationIndex: 12, envelope: { attack: 0.001, decay: 1.2, sustain: 0 }, modulationEnvelope: { attack: 0.001, decay: 0.6, sustain: 0 }, volume: -12 }).connect(out) }),
  hit: (T, n, p, t) => { n.f.set({ harmonicity: 2.5 + p.color * 4.01, modulationIndex: 4 + p.snap * 20, envelope: { decay: p.dec * 2 } }); n.f.triggerAttackRelease(mf(T, 72 + p.tune * 24), p.dec * 2, t, p.vel); } };
V.gong = { label: 'gong', make: (T, out) => ({ m: new T.MetalSynth({ envelope: { attack: 0.002, decay: 1.5, release: 0.5 }, harmonicity: 1.4, modulationIndex: 20, resonance: 800, octaves: 2, volume: -18 }).connect(out) }),
  hit: (T, n, p, t) => { n.m.set({ envelope: { decay: p.dec * 3 }, harmonicity: 1.2 + p.color * 3, modulationIndex: 8 + p.snap * 30 }); n.m.triggerAttackRelease(mf(T, 48 + p.tune * 12), p.dec * 3, t, p.vel * 0.9); } };
V.zap = { label: 'zap', make: (T, out) => ({ o: new T.Synth({ oscillator: { type: 'sawtooth' }, envelope: { attack: 0.001, decay: 0.2, sustain: 0 }, volume: -10 }).connect(out) }),
  hit: (T, n, p, t) => { const f = mf(T, 48 + p.tune * 24), d = Math.max(0.05, p.dec * 0.4); n.o.set({ envelope: { decay: d } }); n.o.oscillator.frequency.setValueAtTime(f * (4 + p.snap * 12), t); n.o.oscillator.frequency.exponentialRampToValueAtTime(f * (0.5 + p.color), t + d * 0.6); n.o.triggerAttackRelease(f, d, t, p.vel); } };
V.glitch = { label: 'glitch', make: (T, out) => { const cr = new T.BitCrusher({ bits: 4 }).connect(out); return { cr, n: new T.NoiseSynth({ noise: { type: 'white' }, envelope: { attack: 0.001, decay: 0.06, sustain: 0 }, volume: -10 }).connect(cr) }; },
  hit: (T, n, p, t) => { n.cr.bits = 2 + Math.round((1 - p.color) * 6); const k = 1 + Math.round(p.snap * 5); for (let i = 0; i < k; i++) n.n.triggerAttackRelease(0.01 + p.dec * 0.05, t + i * (0.015 + p.dec * 0.02), p.vel * (1 - i / (k + 1))); } };
V.snap = { label: 'snap', make: (T, out) => ({ n: new T.NoiseSynth({ noise: { type: 'white' }, envelope: { attack: 0.0005, decay: 0.03, sustain: 0 }, volume: -6 }).connect(out) }),
  hit: (T, n, p, t) => { n.n.set({ envelope: { decay: 0.01 + p.dec * 0.08 } }); n.n.triggerAttackRelease(0.01 + p.dec * 0.08, t, p.vel); } };
export const VOICES = V;
export const VOICE_KEYS = Object.keys(V);
