// Lights Out on the Move: pads are the lights. Puzzles are generated by random presses from the solved state,
// so every puzzle is solvable and the generating press-set (kept up to date as you play) doubles as the hint.
import { Midi } from '../midi.js';
import { MoveDevice, COLOR, padAt, padRowCol, nearestPaletteIndex } from 'movewire';
import { Audio } from '../audio.js';
import { Arp } from './arp.js';
import { getTempo, onTempo } from '../tempo.js';

const $ = (id) => document.getElementById(id);
const midi = new Midi();
const move = new MoveDevice({ send: (b) => midi.send(b) });
midi.addEventListener('raw', (e) => move.receive(e.detail.bytes, e.detail.t));
const audio = new Audio();
const arp = new Arp(audio); let arpOn = true; arp.setTempo(getTempo(112)); onTempo((bpm) => arp.setTempo(bpm));
const litCells = () => [...lights].map(p => padRowCol(p));
function arpEvolve(won = false) { if (!arpOn) return; arp.evolve({ lit: litCells(), level, won, cols }); }
function arpStart() { if (!arpOn || arp.running) return; try { audio.ensure(); arp.start(); } catch {} }
// any first interaction unlocks audio (Chrome keeps the context suspended until a gesture)
for (const ev of ['pointerdown', 'keydown']) window.addEventListener(ev, () => { audio.ensure(); arpStart(); }, { once: true });

const ROWS = 4;
let cols = 8, level = 4, lights = new Set(), solution = new Set(), history = [], moves = 0, won = false, hintPad = null;
const LED = { on: nearestPaletteIndex('#fde047'), off: COLOR.OFF, hint: COLOR.WHITE, won: COLOR.GREEN, outside: COLOR.OFF };
const inBoard = (pad) => { const { col } = padRowCol(pad); return col < cols; };
const neighbours = (pad) => { const { row, col } = padRowCol(pad); const n = [pad]; if (row > 0) n.push(padAt(row - 1, col)); if (row < ROWS - 1) n.push(padAt(row + 1, col)); if (col > 0) n.push(padAt(row, col - 1)); if (col < cols - 1) n.push(padAt(row, col + 1)); return n; };
const flip = (set, pad) => (set.has(pad) ? set.delete(pad) : set.add(pad));
const toggleSym = (set, pad) => flip(set, pad);

function press(pad, { record = true } = {}) {
  for (const n of neighbours(pad)) flip(lights, n);
  toggleSym(solution, pad);
  if (record) { history.push(pad); moves++; }
}
function newPuzzle() {
  lights = new Set(); solution = new Set(); history = []; moves = 0; won = false; hintPad = null;
  const cells = []; for (let r = 0; r < ROWS; r++) for (let c = 0; c < cols; c++) cells.push(padAt(r, c));
  let tries = 0;
  do { lights.clear(); solution.clear(); for (let i = 0; i < level; i++) press(cells[Math.floor(Math.random() * cells.length)], { record: false }); tries++; } while (lights.size === 0 && tries < 20);
  $('par').textContent = solution.size; $('msg').textContent = ''; render();
  arp.newSong(); arpEvolve(); arpStart();
}
function undo() { const pad = history.pop(); if (pad == null) return; press(pad, { record: false }); moves = Math.max(0, moves - 1); won = false; hintPad = null; arpEvolve(); render(); }
function hint() { if (won || !solution.size) return; hintPad = [...solution][0]; audio.ensure(); audio.tone(72, 0.15); render(); setTimeout(() => { hintPad = null; render(); }, 900); }
function onPad(pad) {
  if (won || !inBoard(pad)) return;
  press(pad); hintPad = null; audio.ensure(); arpStart(); if (!arpOn) audio.tone(lights.has(pad) ? 60 : 67, 0.12);
  if (lights.size === 0) { won = true; const key = `midi-warz.lights.best.${cols}.${level}`; const b = +localStorage.getItem(key) || 0; if (!b || moves < b) { try { localStorage.setItem(key, moves); } catch {} } $('msg').textContent = moves <= +$('par').textContent ? `Out in ${moves}. Par. ✨` : `Out in ${moves} (par ${$('par').textContent}).`; if (!arpOn) [64, 67, 71, 76].forEach((n, i) => setTimeout(() => audio.tone(n, 0.25), i * 90)); }
  arpEvolve(won); render();
}

// ---- screen + LEDs ----
const cells = new Map();
function build() {
  const el = $('lo'); el.innerHTML = ''; cells.clear(); el.style.gridTemplateColumns = `repeat(${cols}, 56px)`;
  for (let r = ROWS - 1; r >= 0; r--) for (let c = 0; c < cols; c++) { const pad = padAt(r, c), d = document.createElement('div'); d.className = 'lo-c'; d.onclick = () => onPad(pad); el.appendChild(d); cells.set(pad, d); }
}
function render() {
  for (const [pad, d] of cells) { d.classList.toggle('on', lights.has(pad)); d.classList.toggle('hint', pad === hintPad); d.classList.toggle('won', won); }
  $('moves').textContent = moves; $('lit').textContent = lights.size;
  $('best').textContent = localStorage.getItem(`midi-warz.lights.best.${cols}.${level}`) || '—';
  if (move.inControl) for (let pad = 0; pad < 32; pad++) move.setPadColor(pad, !inBoard(pad) ? LED.outside : pad === hintPad ? LED.hint : won ? LED.won : lights.has(pad) ? LED.on : LED.off);
}
$('size').onchange = () => { cols = +$('size').value; build(); newPuzzle(); };
$('level').onchange = () => { level = Math.min(20, Math.max(1, +$('level').value)); $('level').value = level; newPuzzle(); };
$('btn-new').onclick = newPuzzle; $('btn-undo').onclick = undo; $('btn-hint').onclick = hint;
function setArp(on) { arpOn = on; $('arp').checked = on; if (on) { arpStart(); arpEvolve(won); } else arp.stop(); if (move.inControl) move.setButtonColor('mute', on ? 0 : COLOR.WHITE); }
$('arp').onchange = () => setArp($('arp').checked);
$('arp-vol').oninput = () => arp.setVolume(+$('arp-vol').value / 100);

// ---- Move ----
move.addEventListener('pad', (e) => { if (e.detail.on) onPad(e.detail.index); });
move.addEventListener('button', (e) => {
  const { name, pressed } = e.detail; if (!pressed) return;
  if (name === 'play') newPuzzle(); if (name === 'undo') undo(); if (name === 'capture') hint(); if (name === 'mute') setArp(!arpOn);
  if (name === 'layout') { $('size').value = cols === 8 ? '4' : '8'; $('size').onchange(); }
});
move.addEventListener('encoder', (e) => { if (e.detail.index === 0) { $('level').value = Math.min(20, Math.max(1, level + e.detail.delta)); $('level').onchange(); } if (e.detail.index === 7) { $('arp-vol').value = Math.min(100, Math.max(0, +$('arp-vol').value + e.detail.delta * 3)); $('arp-vol').oninput(); } });
function setPill(t, cls) { const el = $('midi-state'); el.textContent = t; el.className = `pill ${cls}`; }
$('btn-connect').onclick = async () => {
  try {
    audio.ensure();
    const { inputs } = await midi.init(); const port = midi.pickDefault(inputs); midi.select(port);
    if (!port) { setPill('Move: no MIDI input found', 'pill-off'); return; }
    if (!midi.sysexAllowed) { setPill('Move: SysEx denied — allow it in the Chrome prompt', 'pill-warn'); return; }
    setPill(`Handshaking with ${port.name}…`, 'pill-warn');
    const { identity } = await move.connect();
    for (const [b, c] of [['play', COLOR.GREEN], ['undo', COLOR.DARK_GREY], ['capture', COLOR.WHITE], ['layout', COLOR.DARK_GREY]]) move.setButtonColor(b, c);
    render(); setPill(`Move: ready${identity ? ` · fw ${identity.major}.${identity.minor}.${identity.build}` : ''}`, 'pill-on'); $('btn-disconnect').disabled = false;
  } catch (e) { setPill(`Move: ${e.message}`, 'pill-off'); }
};
$('btn-disconnect').onclick = () => { move.disconnect(); setPill('Move: disconnected (back to standalone)', 'pill-off'); $('btn-disconnect').disabled = true; };
window.addEventListener('beforeunload', () => { if (move.inControl) move.disconnect(); });
// keyboard: 1-8 / q-i / a-k / z-, = rows top to bottom
const KEYS = ['12345678', 'qwertyui', 'asdfghjk', 'zxcvbnm,'];
window.addEventListener('keydown', (e) => { if (e.repeat || ['INPUT', 'SELECT'].includes(e.target.tagName)) return; const r = KEYS.findIndex(k => k.includes(e.key)); if (r >= 0) onPad(padAt(3 - r, KEYS[r].indexOf(e.key))); if (e.key === 'n') newPuzzle(); if (e.key === 'h') hint(); if (e.key === 'Backspace') undo(); });

window.__lo = { arp, audio, get lights() { return lights; } };
build(); newPuzzle();
