// Tone's addAudioWorkletModule loads a worklet from a blob URL, where ES imports do not resolve. So the processor
// file is generated: dsp-core.js (the maths, also used by the tests) + the processor class, in one self-contained
// script. Run after editing dsp-core.js:  node tools/build-worklet.mjs   (test/poly.test.js checks it is in sync)
import { readFileSync, writeFileSync } from 'node:fs';
const core = readFileSync(new URL('../src/poly/dsp-core.js', import.meta.url), 'utf8').replace(/^export /gm, '');
const out = `// GENERATED by tools/build-worklet.mjs from dsp-core.js — edit those, not this file.
// One AudioWorkletNode per lane: the page posts { t, layers } hits (t = context time, usually a little ahead) and the
// processor starts them on the exact sample. { ping: id } answers { pong: id } once every earlier message is in, so an
// offline render can wait for its hits to arrive before it starts. Silent when idle.
${core}
class OrbitsDsp extends AudioWorkletProcessor {
  constructor() {
    super(); this.eng = makeEngine(sampleRate); this.pending = [];
    this.port.onmessage = ({ data }) => {
      if (data?.layers) this.pending.push(data);
      else if (data?.ping != null) this.port.postMessage({ pong: data.ping });
      else if (data?.panic) { this.pending.length = 0; for (const s of this.eng.slots) s.active = false; }
    };
  }
  process(_inputs, outputs) {
    const out = outputs[0][0]; if (!out) return true;
    const n = out.length, end = currentTime + n / sampleRate;
    if (this.pending.length) {
      let w = 0;
      for (let i = 0; i < this.pending.length; i++) {
        const h = this.pending[i];
        if (h.t < end) { const off = Math.max(0, Math.min(n - 1, Math.round((h.t - currentTime) * sampleRate))); this.eng.hit(h.layers, off); }
        else this.pending[w++] = h;
      }
      this.pending.length = w;
    }
    this.eng.render(out, 0, n);
    return true;
  }
}
registerProcessor('orbits-dsp', OrbitsDsp);
`;
writeFileSync(new URL('../src/poly/dsp-worklet.js', import.meta.url), out); console.log('src/poly/dsp-worklet.js written');
